security:
  oauth2:
    client:
      client-id: laptop
      client-secret: pin
      user-authorization-uri: http://localhost:8181/oauth/authorize
      access-token-uri: http://localhost:8181/oauth/token
    resource:
        token-info-uri: http://localhost:8181/oauth/check_token

server:
  servlet:
    session:
      cookie:
        name: KSESSION
